// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"time"

	"github.com/aberti/cnpg-portal/internal/cnpg"
)

// BackupStatus is the htmx-swapped result fragment for the top-level
// Backup button. Render states:
//   - canTrigger=false       -> muted "admin required" message (no button)
//   - ready=true             -> green "Trigger backup" button
//   - err != ""              -> red message + "Retry" button
//   - b != nil && err == ""  -> success message + "Backup again" button
//
// The button itself fires hx-post="/backup" with hx-disabled-elt so the
// user can't double-click during the ~30–90s wait. CNPG backups are
// cluster-wide, not per-tenant, so this lives in the page header.
func BackupStatus(ready bool, b *cnpg.Backup, err string, canTrigger bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"backup-status\" style=\"display:flex;gap:1rem;align-items:center;\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !canTrigger {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<small style=\"color:var(--pico-color-zinc-500);\">Backup is admin-only.</small>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if ready {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button hx-post=\"/backup\" hx-target=\"#backup-status\" hx-swap=\"outerHTML\" hx-disabled-elt=\"this\" hx-indicator=\"#backup-spinner\"><span class=\"backup-label\">Trigger backup</span> <span id=\"backup-spinner\" class=\"backup-indicator\" aria-busy=\"true\">Backing up… (CNPG backs up the whole cluster, ~30–90s)</span></button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if err != "" {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<small style=\"color:var(--pico-color-red-600);\">backup failed: ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(err)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 30, Col: 71}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</small> <button class=\"secondary\" hx-post=\"/backup\" hx-target=\"#backup-status\" hx-swap=\"outerHTML\">Retry</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else if b != nil {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<small style=\"color:var(--pico-color-green-600);\">✓ ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(b.Name)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 34, Col: 16}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" — completed ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(describeBackup(b))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/web/templates/components.templ`, Line: 34, Col: 52}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</small> <button class=\"secondary\" hx-post=\"/backup\" hx-target=\"#backup-status\" hx-swap=\"outerHTML\">Backup again</button>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<style>\n\t\t\t.backup-indicator { display: none; }\n\t\t\t.htmx-request .backup-indicator { display: inline; }\n\t\t\t.htmx-request .backup-label { display: none; }\n\t\t</style></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

func describeBackup(b *cnpg.Backup) string {
	if b == nil || b.StoppedAt.IsZero() || b.StartedAt.IsZero() {
		return ""
	}
	return fmt.Sprintf("in %s", b.StoppedAt.Sub(b.StartedAt).Round(time.Second))
}

var _ = templruntime.GeneratedTemplate
